name       : haskell-http-client-tls
version    : 0.3.4
release    : 1
source     :
    - http://hackage.haskell.org/package/http-client-tls-0.3.4/http-client-tls-0.3.4.tar.gz : 37693b0ebcfa6ce796abf39647ff4df17361ab1ab1f999ac10faba67d3042bc1
license    : MIT
component  : programming.haskell
summary    : Use the http-client package with the pure-Haskell tls package for secure connections.
description: |
    Use the http-client package with the pure-Haskell tls package for secure connections.
builddeps  :
    - haskell-cabal-install
    - haskell-connection
    - haskell-http-client
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
