name       : haskell-http-client-tls
version    : 0.3.5.3
release    : 2
source     :
    - http://hackage.haskell.org/package/http-client-tls-0.3.5.3/http-client-tls-0.3.5.3.tar.gz : 471abf8f29a909f40b21eab26a410c0e120ae12ce337512a61dae9f52ebb4362
license    : MIT
component  : programming.haskell
summary    : Use the http-client package with the pure-Haskell tls package for secure connections.
description: |
    Use the http-client package with the pure-Haskell tls package for secure connections.
builddeps  :
    - haskell-cabal-install
    - haskell-connection
    - haskell-http-client
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
